<!DOCTYPE html>
<html>
<head>
	<title>PeterKinnaird.eu - {% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="public/style.css">
</head>
<body>
	{% block content %}

	{% endblock content %}
</body>
<script type="text/javascript" src="public/components/foundation/dist/foundation.min.js"></script>
<script type="text/javascript" src="public/components/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="public/components/what-input/what-input.min.js"></script>
</html>