<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
	<title>PeterKinnaird.eu - {% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="/public/style.css">
</head>
<body>
	{% block content %}

	{% endblock content %}
</body>
<script type="text/javascript" src="/public/vendor.min.js"></script>
<script type="text/javascript" src="/public/index.min.js"></script>
</html>