<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
	<title>PeterKinnaird.eu - {% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="/public/style.css">
	<script type="text/javascript" src="/public/vendor.js"></script>
	<script type="text/javascript" src="/public/index.min.js"></script>
</head>
<body>
	{% block content %}

	{% endblock content %}
	
</body>

</html>